version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: go-dbase-container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goDB
  app:
    build: ./studyProject
    container_name: go-app-study
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=goDB
    depends_on:
      - db
    restart: always
  # User Service
  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "8082:8082"
    restart: always

  # Keycloak DB
  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    restart: always
    ports:
      - "8081:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak-db



