// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "studyProject/entity"

	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// AddCourse provides a mock function with given fields: course
func (_m *CourseRepository) AddCourse(course entity.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for AddCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCourse provides a mock function with given fields: id
func (_m *CourseRepository) DeleteCourse(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCourses provides a mock function with no fields
func (_m *CourseRepository) GetAllCourses() ([]entity.Course, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourses")
	}

	var r0 []entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Course, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Course); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourse provides a mock function with given fields: id
func (_m *CourseRepository) GetCourse(id int) (entity.Course, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.Course, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.Course); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Course)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCourse provides a mock function with given fields: updateCourse
func (_m *CourseRepository) UpdateCourse(updateCourse entity.Course) error {
	ret := _m.Called(updateCourse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Course) error); ok {
		r0 = rf(updateCourse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
