// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "studyProject/entity"

	mock "github.com/stretchr/testify/mock"
)

// ChapterService is an autogenerated mock type for the ChapterService type
type ChapterService struct {
	mock.Mock
}

// AddChapter provides a mock function with given fields: chapter
func (_m *ChapterService) AddChapter(chapter entity.Chapter) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for AddChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Chapter) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChapter provides a mock function with given fields: id
func (_m *ChapterService) DeleteChapter(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllChapters provides a mock function with no fields
func (_m *ChapterService) GetAllChapters() ([]entity.Chapter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllChapters")
	}

	var r0 []entity.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Chapter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Chapter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChapter provides a mock function with given fields: id
func (_m *ChapterService) GetChapter(id int) (entity.Chapter, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChapter")
	}

	var r0 entity.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.Chapter, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.Chapter); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Chapter)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChapter provides a mock function with given fields: updateChapter
func (_m *ChapterService) UpdateChapter(updateChapter entity.Chapter) error {
	ret := _m.Called(updateChapter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Chapter) error); ok {
		r0 = rf(updateChapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterService creates a new instance of ChapterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterService {
	mock := &ChapterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
