// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "studyProject/entity"

	mock "github.com/stretchr/testify/mock"
)

// LessonRepository is an autogenerated mock type for the LessonRepository type
type LessonRepository struct {
	mock.Mock
}

// AddLesson provides a mock function with given fields: lesson
func (_m *LessonRepository) AddLesson(lesson entity.Lesson) error {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for AddLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Lesson) error); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLesson provides a mock function with given fields: id
func (_m *LessonRepository) DeleteLesson(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllLessons provides a mock function with no fields
func (_m *LessonRepository) GetAllLessons() ([]entity.Lesson, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllLessons")
	}

	var r0 []entity.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Lesson, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Lesson); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLesson provides a mock function with given fields: id
func (_m *LessonRepository) GetLesson(id int) (entity.Lesson, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLesson")
	}

	var r0 entity.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.Lesson, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.Lesson); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Lesson)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLesson provides a mock function with given fields: updateLesson
func (_m *LessonRepository) UpdateLesson(updateLesson entity.Lesson) error {
	ret := _m.Called(updateLesson)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLesson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Lesson) error); ok {
		r0 = rf(updateLesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLessonRepository creates a new instance of LessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LessonRepository {
	mock := &LessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
